import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/redux/provider";
import { AuthenticatedLayout } from "@/hooks/AuthenticatedLayout";
import Spinner from "./components/Spinner";
import SideBar from "./components/SideBar";
import { Banner } from "@/assets";
import Image from "next/image";
import DeviceDetector from "./components/DeviceDetector";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>MIP</title>
      </head>
      <body className={`antialiased h-screen w-screen bg-[#0a0a0a]`}>
        <Providers>
        <DeviceDetector />
          <Spinner></Spinner>
          <AuthenticatedLayout>
            <Image
              src={Banner}
              alt="banner"
              height={1440}
              width={1440}
              className="object-cover w-screen h-screen absolute top-0 left-0 -z-50"
            />
            <div className="flex lg:flex-row flex-col">
              <SideBar />
              {children}
            </div>
          </AuthenticatedLayout>
        </Providers>
      </body>
    </html>
  );
}
